### ISSUE TITLE
Using with Storybook v6

### ISSUE THREAD

**Issue by jdortegar** [focusreactive/storybook-graphql-kit#2]
Hey guys!

Great add-on, I just have one question, my API doesn't request an auth, but I saw that the decorator need a token to run, exists any workaround to don't use the token ??

**Comment by jdortegar** [comment]
Nevermind, I did it!

**Comment by jdortegar** [comment]
Hey guys! it's me again, I' trying to implement your add-on and now I have this issue when I try to use the `graphQlResponse` argument

```js
export const speakers = ({ graphQlResponse }) => {
  const data = graphQlResponse.result;
  console.log(data);
  return null;
  // or pass data to your components
};
```

<details>
  <summary>
index.js:287 Uncaught RangeError: Maximum call stack size exceeded
  </summary>

```console
index.js:287 Uncaught RangeError: Maximum call stack size exceeded
    at sortObject (index.js:287)
    at index.js:314
    at Array.reduce (<anonymous>)
    at sortObject (index.js:304)
    at index.js:314
    at Array.reduce (<anonymous>)
    at sortObject (index.js:304)
    at index.js:314
    at Array.reduce (<anonymous>)
    at sortObject (index.js:304)
sortObject @ index.js:287
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
sortObject @ index.js:304
(anonymous) @ index.js:314
Promise.then (async)
asyncGeneratorStep @ StoryRenderer.js:64
_next @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
renderStory @ StoryRenderer.js:469
_callee2$ @ StoryRenderer.js:302
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ StoryRenderer.js:64
_next @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
renderStoryIfChanged @ StoryRenderer.js:326
_callee$ @ StoryRenderer.js:194
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ StoryRenderer.js:64
_next @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
renderCurrentStory @ StoryRenderer.js:208
(anonymous) @ StoryRenderer.js:121
(anonymous) @ index.js:196
handleEvent @ index.js:195
handler @ index.js:121
emit @ index.js:128
finishConfiguring @ story_store.js:486
ConfigApi.configure @ config_api.js:33
(anonymous) @ loadCsf.js:333
configure @ index.js:35
(anonymous) @ generated-stories-entry.js:6
./.storybook/generated-stories-entry.js @ generated-stories-entry.js:6
__webpack_require__ @ bootstrap:848
hotApplyInternal @ bootstrap:749
hotApply @ bootstrap:411
cb @ process-update.js:76
(anonymous) @ process-update.js:91
Promise.then (async)
check @ process-update.js:90
push../node_modules/webpack-hot-middleware/process-update.js.module.exports @ process-update.js:52
processMessage @ client.js:279
handleMessage @ client.js:139
handleMessage @ client.js:102
Show 209 more frames
react-dom.development.js:20085 The above error occurred in one of your React components:

    at LocationProvider (http://localhost:6006/vendors~main.ee414e5618a2486af18a.bundle.js:88089:5)
    at unboundStoryFn (http://localhost:6006/vendors~main.ee414e5618a2486af18a.bundle.js:104753:30)
    at ErrorBoundary (http://localhost:6006/vendors~main.ee414e5618a2486af18a.bundle.js:119491:5)

React will try to recreate this component tree from scratch using the error boundary you provided, LocationProvider.
logCapturedError @ react-dom.development.js:20085
callback @ react-dom.development.js:20154
callCallback @ react-dom.development.js:12318
commitUpdateQueue @ react-dom.development.js:12339
commitLifeCycles @ react-dom.development.js:20709
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
scheduleUpdateOnFiber @ react-dom.development.js:21881
updateContainer @ react-dom.development.js:25482
(anonymous) @ react-dom.development.js:26021
unbatchedUpdates @ react-dom.development.js:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
(anonymous) @ render.js:84
render @ render.js:83
_callee$ @ render.js:176
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ render.js:54
_next @ render.js:56
(anonymous) @ render.js:56
(anonymous) @ render.js:56
renderMain @ render.js:148
_callee3$ @ StoryRenderer.js:437
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ StoryRenderer.js:64
_next @ StoryRenderer.js:66
Promise.then (async)
asyncGeneratorStep @ StoryRenderer.js:64
_next @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
renderStory @ StoryRenderer.js:469
_callee2$ @ StoryRenderer.js:302
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ StoryRenderer.js:64
_next @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
renderStoryIfChanged @ StoryRenderer.js:326
_callee$ @ StoryRenderer.js:194
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ StoryRenderer.js:64
_next @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
renderCurrentStory @ StoryRenderer.js:208
(anonymous) @ StoryRenderer.js:121
(anonymous) @ index.js:196
handleEvent @ index.js:195
handler @ index.js:121
emit @ index.js:128
finishConfiguring @ story_store.js:486
ConfigApi.configure @ config_api.js:33
(anonymous) @ loadCsf.js:333
configure @ index.js:35
(anonymous) @ generated-stories-entry.js:6
./.storybook/generated-stories-entry.js @ generated-stories-entry.js:6
__webpack_require__ @ bootstrap:848
hotApplyInternal @ bootstrap:749
hotApply @ bootstrap:411
cb @ process-update.js:76
(anonymous) @ process-update.js:91
Promise.then (async)
check @ process-update.js:90
push../node_modules/webpack-hot-middleware/process-update.js.module.exports @ process-update.js:52
processMessage @ client.js:279
handleMessage @ client.js:139
handleMessage @ client.js:102
Show 46 more frames
index.js:81 Uncaught RangeError: Maximum call stack size exceeded
    at sortObject (index.js:287)
    at index.js:314
    at Array.reduce (<anonymous>)
    at sortObject (index.js:304)
    at index.js:314
    at Array.reduce (<anonymous>)
    at sortObject (index.js:304)
    at index.js:314
    at Array.reduce (<anonymous>)
    at sortObject (index.js:304)
componentDidCatch @ index.js:81
callback @ react-dom.development.js:20159
callCallback @ react-dom.development.js:12318
commitUpdateQueue @ react-dom.development.js:12339
commitLifeCycles @ react-dom.development.js:20709
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
scheduleUpdateOnFiber @ react-dom.development.js:21881
updateContainer @ react-dom.development.js:25482
(anonymous) @ react-dom.development.js:26021
unbatchedUpdates @ react-dom.development.js:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
(anonymous) @ render.js:84
render @ render.js:83
_callee$ @ render.js:176
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ render.js:54
_next @ render.js:56
(anonymous) @ render.js:56
(anonymous) @ render.js:56
renderMain @ render.js:148
_callee3$ @ StoryRenderer.js:437
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ StoryRenderer.js:64
_next @ StoryRenderer.js:66
Promise.then (async)
asyncGeneratorStep @ StoryRenderer.js:64
_next @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
renderStory @ StoryRenderer.js:469
_callee2$ @ StoryRenderer.js:302
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ StoryRenderer.js:64
_next @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
renderStoryIfChanged @ StoryRenderer.js:326
_callee$ @ StoryRenderer.js:194
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ StoryRenderer.js:64
_next @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
renderCurrentStory @ StoryRenderer.js:208
(anonymous) @ StoryRenderer.js:121
(anonymous) @ index.js:196
handleEvent @ index.js:195
handler @ index.js:121
emit @ index.js:128
finishConfiguring @ story_store.js:486
ConfigApi.configure @ config_api.js:33
(anonymous) @ loadCsf.js:333
configure @ index.js:35
(anonymous) @ generated-stories-entry.js:6
./.storybook/generated-stories-entry.js @ generated-stories-entry.js:6
__webpack_require__ @ bootstrap:848
hotApplyInternal @ bootstrap:749
hotApply @ bootstrap:411
cb @ process-update.js:76
(anonymous) @ process-update.js:91
Promise.then (async)
check @ process-update.js:90
push../node_modules/webpack-hot-middleware/process-update.js.module.exports @ process-update.js:52
processMessage @ client.js:279
handleMessage @ client.js:139
handleMessage @ client.js:102
Show 46 more frames
react-dom.development.js:20085 The above error occurred in the <LocationProvider> component:

    at LocationProvider (http://localhost:6006/vendors~main.ee414e5618a2486af18a.bundle.js:88089:5)
    at unboundStoryFn (http://localhost:6006/vendors~main.ee414e5618a2486af18a.bundle.js:104753:30)
    at ErrorBoundary (http://localhost:6006/vendors~main.ee414e5618a2486af18a.bundle.js:119491:5)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-dom.development.js:20085
update.payload @ react-dom.development.js:20133
getStateFromUpdate @ react-dom.development.js:12102
processUpdateQueue @ react-dom.development.js:12250
updateClassInstance @ react-dom.development.js:13013
updateClassComponent @ react-dom.development.js:17432
beginWork @ react-dom.development.js:19073
beginWork$1 @ react-dom.development.js:23940
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
unbatchedUpdates @ react-dom.development.js:22438
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
(anonymous) @ render.js:84
render @ render.js:83
_callee$ @ render.js:176
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ render.js:54
_next @ render.js:56
(anonymous) @ render.js:56
(anonymous) @ render.js:56
renderMain @ render.js:148
_callee3$ @ StoryRenderer.js:437
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ StoryRenderer.js:64
_next @ StoryRenderer.js:66
Promise.then (async)
asyncGeneratorStep @ StoryRenderer.js:64
_next @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
renderStory @ StoryRenderer.js:469
_callee2$ @ StoryRenderer.js:302
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ StoryRenderer.js:64
_next @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
renderStoryIfChanged @ StoryRenderer.js:326
_callee$ @ StoryRenderer.js:194
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ StoryRenderer.js:64
_next @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
(anonymous) @ StoryRenderer.js:66
renderCurrentStory @ StoryRenderer.js:208
(anonymous) @ StoryRenderer.js:121
(anonymous) @ index.js:196
handleEvent @ index.js:195
handler @ index.js:121
emit @ index.js:128
finishConfiguring @ story_store.js:486
ConfigApi.configure @ config_api.js:33
(anonymous) @ loadCsf.js:333
configure @ index.js:35
(anonymous) @ generated-stories-entry.js:6
./.storybook/generated-stories-entry.js @ generated-stories-entry.js:6
__webpack_require__ @ bootstrap:848
hotApplyInternal @ bootstrap:749
hotApply @ bootstrap:411
cb @ process-update.js:76
(anonymous) @ process-update.js:91
Promise.then (async)
check @ process-update.js:90
push../node_modules/webpack-hot-middleware/process-update.js.module.exports @ process-update.js:52
processMessage @ client.js:279
handleMessage @ client.js:139
handleMessage @ client.js:102
Show 46 more frames
index.js:60 RangeError: Maximum call stack size exceeded
    at sortObject (index.js:287)
    at index.js:314
    at Array.reduce (<anonymous>)
    at sortObject (index.js:304)
    at index.js:314
    at Array.reduce (<anonymous>)
    at sortObject (index.js:304)
    at index.js:314
    at Array.reduce (<anonymous>)
    at sortObject (index.js:304)
```
</details>

Without the argument I can see the table with the graphql response, any clue about this ?

```
export const speakers = () => {
  // const data = graphQlResponse.result;
  // console.log(data);
  return null;
  // or pass data to your components
};
```

![image](https://user-images.githubusercontent.com/43345955/104745419-12bcdc80-571c-11eb-8872-2fc04227904f.png)

**Comment by jdortegar** [comment]
any news here @operatino @UsulPro ??

**Comment by usulpro** [comment]
Hey @jdortegar 

Thanks for reporting this. Sorry it takes time to investigate what happened.
It looks like you're using this addon with Storybook v6. And this version contain breaking changes that breaks the addon indeed.

If it's the case we can temporary use a workaround:

```js
export const speakers = (_, { graphQlResponse }) => {
  const data = graphQlResponse.result;
  console.log(data);
  return null;
  // or pass data to your components
};
```

basically get it from the second argument
 
Note: it will be solved in the next version of the addon. So you would need to switch it back.

Let me know if it helps please

**Comment by usulpro** [comment]
solved in v1.0.2

**Comment by jdortegar** [comment]
Hello @UsulPro!

Thanks for your answer, unfortunately, it doesn't work well for me, when I added the decorator as a global configuration, my graphql story works but the other stories return the default table empty.

If I add the decorator at the story level, i get this errors:
![image](https://user-images.githubusercontent.com/43345955/108734464-4276b580-750e-11eb-8c5e-47af78a69dcc.png)

![image](https://user-images.githubusercontent.com/43345955/108734181-f592df00-750d-11eb-8b2c-7a5e485568e0.png)

Here is my complete story file
```
import React, { useEffect } from "react";
// also exported from '@storybook/react' if you can deal with breaking changes in 6.1
import { Story, Meta } from "@storybook/react/types-6-0";
import {
  QueryParams,
  withGraphQL,
} from "@focus-reactive/storybook-graphql-kit";

import { buildComponentStack } from "./StackBuilder";

const query = /* GraphQL */ `
  query EXPLORES_QUERY($exploreSlug: String!) {
    explores(where: { slug: $exploreSlug }) {
      id
      slug
      stack {
        __typename
        ... on ComponentLayoutGalleryContainer {
          id
        }
      }
    }
  }
`;

export default {
  title: "Components/StackBuilderCMS",
} as Meta;

export const Default = ({ graphQlResponse }) => {
  const data = graphQlResponse.result;

  console.log(data);
  return null;
};

Default.decorators = [
  withGraphQL({
    endpoint: "https://alameda-staging.herokuapp.com/graphql",
  }),
];

Default.story = {
  name: "ExploreStackBuilder",
  parameters: QueryParams({
    endpoint: "https://alameda-staging.herokuapp.com/graphql",
    query,
    searchVars: { exploreSlug: "all-weather-covers" },
    isConnected: true,
  }),
};

```

**Comment by jdortegar** [comment]
Waiting response to finish this https://github.com/LiveOuter/webstore/pull/214 @UsulPro
